Create check-encoding.yml
mimosa-project/mmlfiles pull request #1
Opened 2021-06-03 13:27 UTC by etmula

# Summary
CIの作成

# Detail
- 文字コードをチェックするCIを作成しました。
- PR時に変更点の文字コードをチェックし、(ASCII or UTF-8)以外の文字コードを含む変更があった場合にCIが失敗します。

# Reference
- https://github.com/2DegreesInvesting/resources/issues/53

2021-06-10 06:21 UTC, aabaa requested changes
ドキュメントを調べてもコマンドの意味が分からないので，分かるように書き換える or ドキュメントを探す

2021-06-10 07:24 UTC, aabaa commented
```sh
! file --mime "${files[@]}" | grep -v "charset=utf-8\|charset=us-ascii\|charset=binary"
```
の感嘆符ですが，これはgrepコマンドの終了ステータスを反転させるためのようです．
grepはマッチすれば0, マッチしなければ1ですが，この場合は-vオプションがついているので，マッチしないものがあれば1を返します．

また，終了ステータスが0以外だとGitHub Actionsはエラーを返す仕組みとのことでした
https://docs.github.com/ja/actions/creating-actions/setting-exit-codes-for-actions

2021-06-10 08:51 UTC, aabaa commented
シェルスクリプトのコマンド置換```$(command)```で末尾の改行が削除されるのは仕様でした
https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html

2021-06-10 14:19 UTC, etmula commented
調査ありがとうございます。
以下のコマンドでチェックするように変更しました。
`files=$(find ./abstr/*.abs)`は、findコマンドにより生成された配列をfilesに代入しています。
`! file --mime-encoding ${files[@]} | grep -v "utf-8\|us-ascii\|binary"`は、
` file --mime-encoding ${files[@]} `でファイルの文字コードを出力します。
`grep -v "utf-8\|us-ascii\|binary`で、出力された文字コードがutf-8, us-ascii, binaryではない行を出力します。
調べていただいた通り、`!`でexitコードを反転し、CIを終了させます。
```
files=$(find ./abstr/*.abs)
! file --mime-encoding ${files[@]} | grep -v "utf-8\|us-ascii\|binary"
```

2021-06-11 00:44 UTC, aabaa approved these changes

2021-06-11 00:44 UTC, merged